#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Running Git Hooks'
{{typeCheck}}
echo "\n🔎 Running linter.."

yarn lint || (
    echo '\n⛔️ There is a problem in the code. ⌛️ I run linter autofix for you.';

    echo '\n🔎 Running linter autofix..'
    yarn lint:fix || (
      echo '\n⛔️ Autofix failed. Please fix the linting errors manually. ⛔️';
      false;
    )

    echo '\n🧐 Please check the changes and commit again.\n'
    false;
    )

echo '✅ No Eslint error found'
echo '⌛️ Running lint staged and git commit ⌛️'

npx lint-staged